### ISSUE TITLE
Gridded Population data is quite suspect, causing bad PW density data

### ISSUE THREAD

**Issue by glacialcascade** [kavigupta/population-density-metric#112]
I was looking at the top few subnational regions by PW Density and a few of them seemed off, particularly:
* Nuevo Leon (listed population is 10.2M, compared to its population of around 5.8M from other sources)
* Beyrouth and Mont-Liban, Lebanon (again populations are way higher than expected)
* Bāgmatī, Nepal (same deal)

I ended up actually downloading the data myself (albeit at a lower resolution) to check if it was actually from the original data source, and it is: it seems that there are anomalies in a few areas in particular.

* The two squares in this image (random area north of Monterrey) supposedly have populations of 1.7M and 1M, respectively
![image](https://github.com/kavigupta/population-density-metric/assets/11969863/58cdf589-836d-4907-9481-8c1733e01155)
* The two squares here just south of Beirut supposedly have populations of 785k and 1.3M.
![image](https://github.com/kavigupta/population-density-metric/assets/11969863/e7640e2e-a388-4b3c-81f6-a955459b9eab)
* These four squares have populations of 1.4M, 1.2M, 1M, 1.1M. 
![image](https://github.com/kavigupta/population-density-metric/assets/11969863/09080bd9-e4e2-4876-8aad-080b3d211acb)

This issue isn't that important and it's probably not fixable at all (unless somehow there's another usable dataset), but it's annoying that it has an outsized effect on the PW metrics (Nuevo Leon is listed as #1 for both 1km and 2km radii, and I think the vast majority of it comes solely from these two squares).

**Comment by kavigupta** [comment]
Working on this. The EU has some better estimates on this and I'll incorporate the data when i get a chance
