### ISSUE TITLE
Toggle for showing other relevant boundaries

### ISSUE THREAD

**Issue by ealgase** [kavigupta/population-density-metric#33]
Would be nice to declutter the interface and allow people to customize their view.

Should look like this
![image](https://github.com/kavigupta/population-density-metric/assets/11603778/0ec4cda9-c762-44e3-b680-d161e8724aa4)

**Comment by kavigupta** [comment]
Thanks! Will take a look

**Comment by kavigupta** [comment]
Ok pushed a change for this, should be up soon

**Comment by kavigupta** [comment]
ok I think this is done. reopen if you disagree
